spring:
  profiles:
    active: local

  application:
    name: saffron-api

  config:
    import:
      - "secret.yml"
      - "saffron_eai.yml"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.server.url}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    com.saffron.api.portal.mapper: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info



